easy_admin:
  design:
    menu:
      - label: 'Menu compliqué'
        children:
          - User
          - Booking
          - Event
          - MenuAdmin
          - ViewAdmin
          - Article
          - ActivityType
          - Activity
          - Round
          - Parrainer
#      - { label: 'Admin' }
#
#      - Menu
#      - View
#      - { label: 'Moderateur' }
      - label: 'Menu simple'
        children:
          - { label: 'Utilisateurs', entity: UserLight, default: true }
          - { label: 'Tables de JDR', entity: ActivityRPG }

  entities:
    User:
      class: App\Entity\User






    Booking:
      class: App\Entity\Booking

    MenuAdmin:
      class: App\Entity\Menu
      list:
        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
          - { property: 'image', type: 'image', base_path: 'uploads/menu' }
          - event
          - color
          - active
          - position
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - name
          - { property: 'color', type: 'choice', type_options: { choices: { bleu: 'bd-bleu', orange: 'bd-orange' }}}
          - active
          - { property: 'imageFile', type: 'vich_image' }
          - event

    ViewAdmin:
      class: App\Entity\View
      list:
        show_sort: false
        fields:
          - name
          - { property: 'image', type: 'image', base_path: 'uploads/view' }
          - menu
          - title
          - subtitle
          - module
          - active
          - fixed
          - deleted
          - position
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - menu
          - title
          - subtitle
          - module
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'fos_ckeditor' }
          - active
          - fixed
          - deleted

    Article:
      class: App\Entity\Article
      list:
        fields:
          - title
          - event
          - active
          - { property: 'image', type: 'image', base_path: 'uploads/article' }
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - title
          - event
          - active
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'fos_ckeditor' }

    Event:
      class: App\Entity\Event
      controller: App\Controller\Admin\EventController
      list:
        actions:
          - { name: 'booking', label: 'Inscriptions', target: '-blank' }
        fields:
          - name
          - start
          - end
          - active
          - open
          - openToPlayers
          - openToMasters

      form:
        fields:
          - name
          - { property: 'start', type: 'datetime', type_options: { widget: 'single_text' } }
          - { property: 'end', type: 'datetime', type_options: { widget: 'single_text' } }
          - active
          - open
          - openToPlayers
          - openToMasters
          - { property: 'options', type: 'collection', type_options: { entry_type: 'App\Form\Field\KeyValueOptionsType' } }
          - { property: 'description', type: 'fos_ckeditor' }
          - { property: 'topLinks', type: 'collection', type_options: { entry_type: 'App\Form\Field\TopLinkType' } }
          - { property: 'footerText', type: 'fos_ckeditor' }
          - facebookLink

    Activity:
      class: App\Entity\Activity
      form:
        fields:
          - name
          - event
          - type
          - { property: 'start', type: 'datetime', type_options: { widget: 'single_text' } }
          - { property: 'end', type: 'datetime', type_options: { widget: 'single_text' } }
          - description
          - game
          - style
          - slots
          - round
          - players
          - master

      list:
        fields:
          - name
          - event
          - type
          - round
          - start
          - end

    ActivityType:
      class: App\Entity\ActivityType
      form:
        fields:
          - name
          - module
      list:
        fields:
          - id
          - name
          - slug
          - module

    Round:
      class: App\Entity\Round
      list:
        fields:
          - id
          - name
          - slug
          - start
          - end
          - event
          - activityType

      form:
        fields:
          - name
          - { property: 'start', type: 'datetime', type_options: { widget: 'single_text' } }
          - { property: 'end', type: 'datetime', type_options: { widget: 'single_text' } }
          - event
          - activityType

    Parrainer:
      class: App\Entity\Parrainer
      list:
        fields:
          - { property: 'image', type: 'image', base_path: 'uploads/parrainer' }
          - name
          - link
          - active
          - event
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - name
          - link
          - active
          - event
          - { property: 'imageFile', type: 'vich_image' }





##############################
#          MENU USER
##############################




    Menu:
      class: App\Entity\Menu
      disabled_actions: ['delete']
      list:
        actions:
          - explore
        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
          - color
          - pic
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

    View:
      class: App\Entity\View
      disabled_actions: ['delete']
      actions: ['explore']
      templates:
        list: '@EasyAdmin/view/list.html.twig'
      list:
#        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
#          - menu
#          - link
          - active
#          - weight
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'fos_ckeditor' }





    UserLight:
      class: App\Entity\User
      disabled_actions: ['delete']
      list:
        fields:
          - username
          - firstName
          - lastName
          - email

      edit:
        fields:
          - username
          - firstName
          - lastName
          - email
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
        form_options: { validation_groups: ['Profile'] }

      new:
        fields:
          - username
          - firstName
          - lastName
          - email
          - { property: 'plainPassword', type: 'text', type_options: { required: true } }
        form_options: { validation_groups: ['Registration'] }

    ActivityRPG:
      class: App\Entity\Activity
      form:
        fields:
          - name
#          - event
#          - type
#          - { property: 'start', type: 'datetime', type_options: { widget: 'single_text' } }
#          - { property: 'end', type: 'datetime', type_options: { widget: 'single_text' } }
          - description
          - game
          - style
          - slots
          - { property: 'round', type_options: { required: true } }
          - players
          - { property: 'master', type_options: { required: true } }

      list:
        dql_filter: 'entity.type = 1'
        sort: ['round', 'ASC']
        fields:
          - name
          - master.username
          - round

      search:
        dql_filter: 'entity.type = 1'
        fields:
          - name
          - master.username
          - round.name

