easy_admin:
  design:
    menu:
      - User
      - Event
      - MenuAdmin
      - Activity
      - ActivityType
      - Round
      - Parrainer
      - ViewAdmin
      - { label: 'Admin' }
      - Global
      - Article
      - Menu
      - View
      - { label: 'Moderateur' }

  entities:
    User:
      class: App\Entity\User

    MenuAdmin:
      class: App\Entity\Menu
      form:
        fields:
          - name
          - { property: 'color', type: 'choice', type_options: { choices: { bleu: 'bd-bleu', orange: 'bd-orange' }}}
          - active
          - { property: 'imageFile', type: 'vich_image' }
          - event

    Event:
      class: App\Entity\Event

    Activity:
      class: App\Entity\Activity

    ActivityType:
      class: App\Entity\ActivityType

    Round:
      class: App\Entity\Round

    Parrainer:
      class: App\Entity\Parrainer

    ViewAdmin:
      class: App\Entity\View
      list:
        fields:
          - name
          - menu
          - title
          - subtitle
          - link
          - active
          - fixed
          - deleted
          - weight

      form:
        fields:
          - name
          - menu
          - link
          - content
          - active
          - fixed
          - deleted
#          - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', type_options: { trim: true } }
          - weight
          - link



##############################
#          MENU USER
##############################

    Global:
      class: App\Entity\GlobalParam
      disabled_actions: ['delete','new']
      form:
        fields:
          - siteName
          - { property: 'mainText', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }

    Article:
      class: App\Entity\Article
      list:
        fields:
          - title
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }
      form:
        fields:
          - title
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }


    Menu:
      class: App\Entity\Menu
      disabled_actions: ['delete']
      list:
        actions:
          - explore
        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
          - color
          - pic
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

    View:
      class: App\Entity\View
      disabled_actions: ['delete']
      actions: ['explore']
      templates:
        list: '@EasyAdmin/view/list.html.twig'
      list:
#        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
#          - menu
#          - link
          - active
#          - weight
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
