easy_admin:
  design:
    menu:
      - label: 'Admin'
        children: ['User', 'Menu', 'Event', 'EventType', 'Round', 'Parrainer', 'View']
      - label: 'Outils'
        children: [ 'Utilisateur', 'Jeux']
  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - username
          - firstname
          - lastname
          - email
          - sleep
          - valid

    Utilisateur:
      class: App\Entity\User
      list:
        fields:
          - username
          - firstname
          - lastname
          - email
          - sleep
          - valid

    Menu:
      class: App\Entity\Menu

    Event:
      class: App\Entity\Event

    Jeux:
      class: App\Entity\Event
      list:
        fields:
          - type
          - name
          - game
          - style
          - round
          - slots

    EventType:
      class: App\Entity\EventType

    Round:
      class: App\Entity\Round

    Parrainer:
      class: App\Entity\Parrainer

    View:
      class: App\Entity\View
      form:
        fields:
          - name
          - menu
          - link
          - content
          - active
#          - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', type_options: { trim: true } }
          - weight
          - link
