easy_admin:
  design:
    menu:
      - User
      - MenuAdmin
      - Event
      - Activity
      - ActivityType
      - Round
      - Parrainer
      - ViewAdmin
      - { label: 'Admin' }
      - Menu
      - View
      - { label: 'Moderateur' }

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - id
          - username
          - firstname
          - lastname
          - email
          - sleep
          - valid

    MenuAdmin:
      class: App\Entity\Menu

    Event:
      class: App\Entity\Event

    Activity:
      class: App\Entity\Activity

    ActivityType:
      class: App\Entity\ActivityType

    Round:
      class: App\Entity\Round

    Parrainer:
      class: App\Entity\Parrainer

    ViewAdmin:
      class: App\Entity\View
      list:
        fields:
          - name
          - menu
          - title
          - subtitle
          - link
          - active
          - fixed
          - deleted
          - weight

      form:
        fields:
          - name
          - menu
          - link
          - content
          - active
          - fixed
          - deleted
#          - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', type_options: { trim: true } }
          - weight
          - link

    Menu:
      class: App\Entity\Menu
      disabled_actions: ['delete']
      list:
        actions:
          - explore
        sort: ['weight', 'ASC']
        show_sort: false
        fields:
          - name
          - color
          - pic
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

    View:
      class: App\Entity\View
      disabled_actions: ['delete']
      actions: ['explore']
      templates:
        list: '@EasyAdmin/view/list.html.twig'
      list:
        sort: ['weight', 'ASC']
        show_sort: false
        fields:
          - name
#          - menu
#          - link
          - active
#          - weight
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
