easy_admin:
  design:
    menu:
      - User
      - Event
      - MenuAdmin
      - ViewAdmin
      - Article
      - Activity
      - Round
      - Parrainer
      - { label: 'Admin' }

      - Menu
      - View
      - { label: 'Moderateur' }

  entities:
    User:
      class: App\Entity\User

    MenuAdmin:
      class: App\Entity\Menu
      list:
        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
          - { property: 'image', type: 'image', base_path: 'uploads/menu' }
          - event
          - color
          - active
          - position
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - name
          - { property: 'color', type: 'choice', type_options: { choices: { bleu: 'bd-bleu', orange: 'bd-orange' }}}
          - active
          - { property: 'imageFile', type: 'vich_image' }
          - event

    ViewAdmin:
      class: App\Entity\View
      list:
        show_sort: false
        fields:
          - name
          - { property: 'image', type: 'image', base_path: 'uploads/view' }
          - menu
          - title
          - subtitle
          - link
          - active
          - fixed
          - deleted
          - position
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - menu
          - title
          - subtitle
          - link
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
          - active
          - fixed
          - deleted
          - link

    Article:
      class: App\Entity\Article
      list:
        fields:
          - title
          - event
          - active
          - { property: 'image', type: 'image', base_path: 'uploads/article' }
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - title
          - event
          - active
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }

    Event:
      class: App\Entity\Event
      form:
        fields:
          - name
          - start
          - end
          - active
          - { property: 'options', type: 'collection', type_options: { entry_type: 'App\Form\Field\KeyValueOptionsType' } }
          - { property: 'description', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }

    Activity:
      class: App\Entity\Activity

    Round:
      class: App\Entity\Round

    Parrainer:
      class: App\Entity\Parrainer
      list:
        fields:
          - { property: 'image', type: 'image', base_path: 'uploads/parrainer' }
          - name
          - link
          - active
          - event
          - { property: 'order', mapped: false, template: 'bundles/EasyAdminBundle/default/field_weight_buttons.html.twig' }
      form:
        fields:
          - name
          - link
          - active
          - event
          - { property: 'imageFile', type: 'vich_image' }





##############################
#          MENU USER
##############################




    Menu:
      class: App\Entity\Menu
      disabled_actions: ['delete']
      list:
        actions:
          - explore
        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
          - color
          - pic
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

    View:
      class: App\Entity\View
      disabled_actions: ['delete']
      actions: ['explore']
      templates:
        list: '@EasyAdmin/view/list.html.twig'
      list:
#        sort: ['position', 'ASC']
        show_sort: false
        fields:
          - name
#          - menu
#          - link
          - active
#          - weight
          - { property: 'order', mapped: false, template: 'admin/field/field_weight_buttons.html.twig' }

      form:
        fields:
          - name
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
