easy_admin:
  design:
    menu:
      - label: 'Admin'
        children: ['User', 'Menu', 'Event', 'EventType', 'Round', 'Parrainer', 'View']

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - id
          - username
          - firstname
          - lastname
          - email
          - sleep
          - valid

    Menu:
      class: App\Entity\Menu

    Event:
      class: App\Entity\Event

    EventType:
      class: App\Entity\EventType

    Round:
      class: App\Entity\Round

    Parrainer:
      class: App\Entity\Parrainer

    View:
      class: App\Entity\View
      list:
        fields:
          - name
          - menu
          - title
          - subtitle
          - link
          - active
          - fixed
          - weight


      form:
        fields:
          - name
          - menu
          - link
          - content
          - active
#          - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', type_options: { trim: true } }
          - weight
          - link
