fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "no-reply@mon-mail.fr"
        sender_name: "no-reply@ mon-mail.fr"