fos_ck_editor:
  default_config: my_config
  configs:
    my_config:
      toolbar: null
      toolbarGroups:
        - { name: 'document', groups: [ 'mode', 'document', 'doctools' ] }
        - { name: 'clipboard', groups: [ 'clipboard', 'undo' ] }
        - { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] }
        - { name: 'forms', groups: [ 'forms' ] }
        - '/'
        - { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] }
        - { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] }
        - { name: 'links', groups: [ 'links' ] }
        - { name: 'insert', groups: [ 'insert' ] }
        - '/'
        - { name: 'styles', groups: [ 'styles' ] }
        - { name: 'colors', groups: [ 'colors' ] }
        - { name: 'tools', groups: [ 'tools' ] }
        - { name: 'others', groups: [ 'others' ] }
        - { name: 'about', groups: [ 'about' ] }

#      removeButtons:
#        - Save
#        - NewPage
#        - Preview
#        - Print
#        ,Templates,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,ImageButton,HiddenField,Language,Font,Flash }