twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        timezones: '@App\Service\TimeZones'
        activityuser: '@App\Service\ActivityUser'
        button: '@App\Service\ActivityButton'
    form_themes: ['bootstrap_4_layout.html.twig']
#    form_themes: ['bootstrap_4_layout.html.twig']
