twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        menu_loader: '@App\Service\MenuLoader'
        timezones: '@App\Service\TimeZones'
        eventuser: '@App\Service\EventUser'
        button: '@App\Service\EventButton'
    form_themes: ['bootstrap_4_layout.html.twig']
#    form_themes: ['bootstrap_4_layout.html.twig']
