vich_uploader:
    db_driver: orm

    mappings:
        view_image:
            uri_prefix: /uploads/view
            upload_destination: '%kernel.project_dir%/public/uploads/view'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        menu_image:
            uri_prefix: /uploads/menu
            upload_destination: '%kernel.project_dir%/public/uploads/menu'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        article_image:
            uri_prefix: /uploads/article
            upload_destination: '%kernel.project_dir%/public/uploads/article'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        parrainer_image:
            uri_prefix: /uploads/parrainer
            upload_destination: '%kernel.project_dir%/public/uploads/parrainer'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer